name: Terraform
on:
  push:
    branches:
    - master
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: '0.12.25'
    - name: Terraform Init
      id: init
      run: terraform init
